CREATE TABLE `wifi` (
	`X_SWIFI_MGR_NO`	VARCHAR(20)	NOT NULL,
	`X_SWIFI_WRDOFC`	VARCHAR(20)	NULL,
	`X_SWIFI_MAIN_NM`	VARCHAR(50)	NULL,
	`X_SWIFI_ADRES1`	VARCHAR(100)	NULL,
	`X_SWIFI_ADRES2`	VARCHAR(100)	NULL,
	`X_SWIFI_INSTL_FLOOR`	VARCHAR(20)	NULL,
	`X_SWIFI_INSTL_TY`	VARCHAR(30)	NULL,
	`X_SWIFI_INSTL_MBY`	VARCHAR(30)	NULL,
	`X_SWIFI_SVC_SE`	VARCHAR(20)	NULL,
	`X_SWIFI_CMCWR`	VARCHAR(20)	NULL,
	`X_SWIFI_CNSTC_YEAR`	VARCHAR(20)	NULL,
	`X_SWIFI_INOUT_DOOR`	VARCHAR(20)	NULL,
	`X_SWIFI_REMARS3`	VARCHAR(100)	NULL,
	`LAT`	VARCHAR(30)	NULL,
	`LNT`	VARCHAR(30)	NULL,
	`WORK_DTTM`	VARCHAR(40)	NULL
);

CREATE TABLE `history` (
	`ID`	INT(10)	NOT NULL	DEFAULT AUTO_INCREMENT,
	`LAT`	VARCHAR(20)	NULL,
	`LNT`	VARCHAR(20)	NULL,
	`SEARCH_DATE`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE `bookmark` (
	`ID`	INT(10)	NOT NULL	DEFAULT AUTO_INCREMENT,
	`BOOKMARKGRP_ID`	INT(10)	NOT NULL,
	`MGR_NO`	VARCHAR(20)	NOT NULL,
	`REGISTRATION_DATE`	DATETIME	NULL	DEFAULT CURRNET_TIMESTAMP()
);

CREATE TABLE `bookmark_group` (
	`ID`	INT(10)	NOT NULL	DEFAULT AUTO_INCREMENT,
	`BOOKMARK_NM`	VARCHAR(20)	NULL,
	`ORDER_NO`	INT(20)	NULL,
	`REGISTRATION_DATE`	DATETIME	NULL	DEFAULT CURRENT_TIMESTAMP(),
	`UPDATE_DATE`	DATETIME	NULL
);

ALTER TABLE `wifi` ADD CONSTRAINT `PK_WIFI` PRIMARY KEY (
	`X_SWIFI_MGR_NO`
);

ALTER TABLE `history` ADD CONSTRAINT `PK_HISTORY` PRIMARY KEY (
	`ID`
);

ALTER TABLE `bookmark` ADD CONSTRAINT `PK_BOOKMARK` PRIMARY KEY (
	`ID`
);

ALTER TABLE `bookmark_group` ADD CONSTRAINT `PK_BOOKMARK_GROUP` PRIMARY KEY (
	`ID`
);

